version: '2.1'
orbs:
  python: circleci/python@1.1.0
jobs:
  build:
    executor:
      name: python/default
      tag: "3.11"
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Test
          command: |
            mkdir test-results
            # Mark pyodide as typed...
            python3.11 -c 'from pathlib import Path; import pyodide; (Path(pyodide.__path__[0]) / "py.typed").write_text("")'
            pytest --junitxml=test-results/junit.xml --verbose --color=yes
      - store_test_results:
          path: test-results
workflows:
  main:
    jobs:
      - build
